### ISSUE TITLE
convert_pytcv_model function

### ISSUE THREAD

**Issue by Andrey-Rogov** [papers-submission/CalibTIP#3]
Hi! I was trying to run _advanced_pipeline.sh_, but unexpectedly get import error: **"ModuleNotFoundError: No module named 'utils.convert_pytcv_model'"** in the first run of _main.py_ in _adaquant.sh_ script. After looking through all the folders, I still can't find **convert_pytcv_model.py**. Could you please add this file to repo or point where is it located?

**Comment by H-xiang-exe** [comment]
you can comment out this line of code.

**Comment by papers-submission** [comment]
I added the file - please pull again
